//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int id_Rating { get; set; }
        public int Teacher_s_Assessment { get; set; }
        public int Manager_s_Assessment { get; set; }
        public decimal Final_Assessment { get; set; }
        public Nullable<int> id_Student { get; set; }
        public Nullable<int> id_Practice { get; set; }
        public Nullable<int> id_Teacher { get; set; }
        public Nullable<int> id_Director { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
